/******************************************************
            Desolation of the Dragon MUD II
      (C) 1997-2002  Jesse DeFer
          http://www.dotd.com  dotd@dotd.com
 ******************************************************/
ACMD(spell_notfound);
ACMD(spell_null);
ACMD(spell_smaug);

/*ACMD(spell_acetum_primus);*/
ACMD(spell_acid_blast);
ACMD(spell_acid_breath);
ACMD(spell_acid_rain);
ACMD(spell_animal_friendship);
ACMD(spell_animate_dead);
ACMD(spell_animate_rock);
ACMD(spell_astral_walk);
/*ACMD(spell_black_fist);*/
/*ACMD(spell_black_hand);*/
/*ACMD(spell_black_lightning);*/
ACMD(spell_blindness);
ACMD(spell_burning_hands);
ACMD(spell_cacaodemon);
ACMD(spell_call_lightning);
ACMD(spell_calm);
/*ACMD(spell_caustic_fount);*/
ACMD(spell_chain_lightning);
ACMD(spell_changestaff);
ACMD(spell_change_sex);
ACMD(spell_charm_person);
ACMD(spell_charm_vegetable);
ACMD(spell_chill_touch);
ACMD(spell_colour_spray);
ACMD(spell_command);
ACMD(spell_conjure_elemental);
ACMD(spell_control_weather);
ACMD(spell_create_food);
ACMD(spell_create_water);
ACMD(spell_cure_blindness);
ACMD(spell_cure_poison);
ACMD(spell_curse);
ACMD(spell_detect_poison);
ACMD(spell_disintegrate);
ACMD(spell_dispel_evil);
ACMD(spell_dispel_good);
ACMD(spell_dispel_magic);
ACMD(spell_disruption);
ACMD(spell_dust_devil);
/*ACMD(spell_dream);*/
ACMD(spell_earthquake);
ACMD(spell_elemental_servant);
ACMD(spell_enchant_armor);
ACMD(spell_enchant_weapon);
ACMD(spell_energy_drain);
/*ACMD(spell_ethereal_fist);*/
ACMD(spell_faerie_fire);
ACMD(spell_faerie_fog);
ACMD(spell_farsight);
ACMD(spell_fear);
ACMD(spell_find_familiar);
ACMD(spell_fire_breath);
ACMD(spell_fireball);
ACMD(spell_flamestrike);
ACMD(spell_flame_blade);
ACMD(spell_frost_breath);
/*ACMD(spell_galvanic_whip);*/
ACMD(spell_gas_breath);
ACMD(spell_gate);
ACMD(spell_golem);
ACMD(spell_gust_of_wind);
/*ACMD(spell_hand_of_chaos);*/
ACMD(spell_harm);
ACMD(spell_haste);
/*ACMD(spell_helical_flow);*/
ACMD(spell_holy_word);
ACMD(spell_identify);
ACMD(spell_invis);
ACMD(spell_knock);
ACMD(spell_know_alignment);
ACMD(spell_know_monster);
ACMD(spell_lightning_bolt);
ACMD(spell_lightning_breath);
ACMD(spell_locate_object);
ACMD(spell_magic_missile);
/*ACMD(spell_magnetic_thrust);*/
/*ACMD(spell_midas_touch);*/
/*ACMD(spell_mind_wrack);*/
/*ACMD(spell_mind_wrench);*/
/*ACMD(spell_mist_walk);*/
ACMD(spell_monsum);
/*ACMD(spell_pass_door);*/
/*ACMD(spell_plant_pass);*/
ACMD(spell_poison);
ACMD(spell_polymorph);
ACMD(spell_portal);
ACMD(spell_possess);
ACMD(spell_prismatic_spray);
ACMD(spell_pword_blind);
ACMD(spell_pword_kill);
/*ACMD(spell_quantum_spike);*/
/*ACMD(spell_recharge);*/
ACMD(spell_refresh);
ACMD(spell_remove_curse);
ACMD(spell_remove_invis);
ACMD(spell_remove_trap);
ACMD(spell_resurection);
ACMD(spell_revive);
/*ACMD(spell_scorching_surge);*/
ACMD(spell_second_wind);
ACMD(spell_shillelagh);
/*ACMD(spell_shocking_grasp);*/
ACMD(spell_silence);
ACMD(spell_sleep);
ACMD(spell_slowness);
/*ACMD(spell_solar_flight);*/
/*ACMD(spell_sonic_resonance);*/
/*ACMD(spell_spectral_furor);*/
/*ACMD(spell_spiral_blast);*/
ACMD(spell_strength);
/*ACMD(spell_sulfurous_spray);*/
ACMD(spell_summon);
ACMD(spell_teleport);
ACMD(spell_transport);
ACMD(spell_ventriloquate);
ACMD(spell_warp_weapon);
ACMD(spell_weaken);
ACMD(spell_web);
ACMD(spell_word_of_recall);
