/******************************************************
            Desolation of the Dragon MUD II
      (C) 1997-2002  Jesse DeFer and Heath Leach
          http://www.dotd.com  dotd@dotd.com
 ******************************************************/

#ifdef ACMD
#if defined(TABLES_C_A) || defined(TABLES_C_ALL)
ACMD(do_aassign);
ACMD(do_acro);
ACMD(do_advance);
ACMD(do_affected);
ACMD(do_afk);
ACMD(do_aid);
ACMD(do_alias);
ACMD(do_allow);
ACMD(do_ansi);
ACMD(do_answer);
ACMD(do_apply);
ACMD(do_appraise);
ACMD(do_areas);
ACMD(do_asave);
ACMD(do_aset);
ACMD(do_ask);
ACMD(do_aspell);
ACMD(do_assist);
ACMD(do_astat);
ACMD(do_at);
ACMD(do_attrib);
ACMD(do_auction);
ACMD(do_authorize);
ACMD(do_avtalk);
#endif
#if defined(TABLES_C_B) || defined(TABLES_C_ALL)
ACMD(do_backstab);
ACMD(do_balance);
ACMD(do_balzhur);
ACMD(do_bamfin);
ACMD(do_bamfout);
ACMD(do_ban);
ACMD(do_bash);
ACMD(do_bashdoor);
ACMD(do_beep);
ACMD(do_bellow);
ACMD(do_berserk);
ACMD(do_bestow);
ACMD(do_bestowarea);
ACMD(do_bet);
ACMD(do_bio);
ACMD(do_bite);
ACMD(do_blast);
ACMD(do_blessing);
ACMD(do_boards);
ACMD(do_bodybag);
ACMD(do_brandish);
ACMD(do_brew);
ACMD(do_bset);
ACMD(do_bstat);
ACMD(do_bug);
ACMD(do_bugtrack);
ACMD(do_bury);
ACMD(do_busy);
ACMD(do_buy);
#endif
#if defined(TABLES_C_C) || defined(TABLES_C_ALL)
ACMD(do_canibalize);
ACMD(do_carve);
ACMD(do_cast);
ACMD(do_cedit);
ACMD(do_chameleon);
ACMD(do_channels);
ACMD(do_check_vnums);
ACMD(do_christen);
ACMD(do_ch_classes);
ACMD(do_clans);
ACMD(do_clantalk);
ACMD(do_claw);
#ifdef IBUILD
ACMD(do_clear);
#endif
ACMD(do_climate);
ACMD(do_climb);
ACMD(do_close);
ACMD(do_cmdtable);
#ifdef IBUILD
ACMD(do_cmenu);
#endif
ACMD(do_color);
ACMD(do_commands);
ACMD(do_comment);
ACMD(do_commodity);
ACMD(do_compare);
ACMD(do_comset);
ACMD(do_config);
ACMD(do_consider);
ACMD(do_cook);
ACMD(do_copyover);
ACMD(do_council_induct);
ACMD(do_council_outcast);
ACMD(do_councils);
ACMD(do_counciltalk);
ACMD(do_credits);
ACMD(do_cset);
ACMD(do_cwhere);
#endif
#if defined(TABLES_C_D) || defined(TABLES_C_ALL)
ACMD(do_deathfield);
ACMD(do_deities);
ACMD(do_delay);
ACMD(do_delete);
ACMD(do_deny);
ACMD(do_deposit);
ACMD(do_description);
ACMD(do_destro);
ACMD(do_destroy);
ACMD(do_detonate);
ACMD(do_detrap);
ACMD(do_devote);
/*ACMD(do_diagnose);*/
ACMD(do_dig);
ACMD(do_disarm);
ACMD(do_disconnect);
ACMD(do_dismount);
ACMD(do_dispel);
ACMD(do_dlookup);
ACMD(do_dmesg);
ACMD(do_donate);
ACMD(do_doorway);
ACMD(do_down);
ACMD(do_drag);
ACMD(do_drain);
ACMD(do_drink);
ACMD(do_drop);
#endif
#if defined(TABLES_C_E) || defined(TABLES_C_ALL)
ACMD(do_east);
ACMD(do_eat);
ACMD(do_echo);
ACMD(do_emote);
ACMD(do_empty);
ACMD(do_enter);
ACMD(do_equipment);
ACMD(do_examine);
ACMD(do_exchange);
ACMD(do_exits);
#endif
#if defined(TABLES_C_F) || defined(TABLES_C_ALL)
ACMD(do_feed);
ACMD(do_feign_death);
ACMD(do_fill);
ACMD(do_find_food);
ACMD(do_find_water);
ACMD(do_fire);
ACMD(do_first_aid);
ACMD(do_fixchar);
ACMD(do_flee);
ACMD(do_foldarea);
ACMD(do_follow);
ACMD(do_for);
ACMD(do_force);
ACMD(do_forceclose);
ACMD(do_forge);
ACMD(do_forget);
ACMD(do_form_password);
ACMD(do_fquit);
ACMD(do_freeze);
#endif
#if defined(TABLES_C_G) || defined(TABLES_C_ALL)
ACMD(do_gain);
ACMD(do_get);
ACMD(do_gfighting);
ACMD(do_give);
ACMD(do_glance);
ACMD(do_gold);
ACMD(do_gossip);
ACMD(do_goto);
ACMD(do_gouge);
ACMD(do_graphviz);
ACMD(do_group);
/*ACMD(do_grub);*/
ACMD(do_gtell);
ACMD(do_guard);
ACMD(do_guilds);
ACMD(do_guildtalk);
#endif
#if defined(TABLES_C_H) || defined(TABLES_C_ALL)
ACMD(do_hedit);
ACMD(do_hell);
ACMD(do_help);
ACMD(do_hide);
ACMD(do_highfive);
ACMD(do_hlist);
ACMD(do_holylight);
ACMD(do_homepage);
ACMD(do_hset);
ACMD(do_hypnotize);
#endif
#if defined(TABLES_C_I) || defined(TABLES_C_ALL)
ACMD(do_ide);
ACMD(do_idea);
/*ACMD(do_ievents);*/
ACMD(do_immortalize);
ACMD(do_induct);
ACMD(do_installarea);
ACMD(do_instaroom);
ACMD(do_instazone);
ACMD(do_intervene);
ACMD(do_interface);
ACMD(do_introduce);
ACMD(do_intuit);
ACMD(do_inventory);
ACMD(do_invis);
ACMD(do_ipcompare);
#ifdef IRC
ACMD(do_irc);
#endif
#endif
#if defined(TABLES_C_J) || defined(TABLES_C_ALL)
ACMD(do_junk);
#endif
#if defined(TABLES_C_K) || defined(TABLES_C_ALL)
ACMD(do_kick);
ACMD(do_kill);
#endif
#if defined(TABLES_C_L) || defined(TABLES_C_ALL)
ACMD(do_languages);
ACMD(do_last);
ACMD(do_lay_on_hands);
ACMD(do_leave);
ACMD(do_legsweep);
ACMD(do_level);
ACMD(do_light);
ACMD(do_list);
ACMD(do_listcurrency);
ACMD(do_litterbug);
ACMD(do_load);
ACMD(do_loadarea);
ACMD(do_loadup);
ACMD(do_lock);
ACMD(do_log);
ACMD(do_look);
ACMD(do_lookmap);
ACMD(do_low_purge);
#endif
#if defined(TABLES_C_M) || defined(TABLES_C_ALL)
ACMD(do_mailroom);
ACMD(do_make);
ACMD(do_makeboard);
ACMD(do_makeclan);
ACMD(do_makecommodity);
ACMD(do_makecouncil);
ACMD(do_makedeity);
/*ACMD(do_makeguild);*/
ACMD(do_makemapfile);
ACMD(do_makeproperty);
ACMD(do_makerepair);
ACMD(do_makeshop);
ACMD(do_makewizlist);
ACMD(do_mapout);
ACMD(do_mapper);
ACMD(do_massign);
ACMD(do_mcreate);
ACMD(do_mdelete);
ACMD(do_meditate);
ACMD(do_memorize);
ACMD(do_memory);
ACMD(do_mfind);
ACMD(do_mind);
ACMD(do_mlist);
#ifdef IBUILD
ACMD(do_mmenu);
#endif
ACMD(do_mount);
ACMD(do_mp_close_passage);
ACMD(do_mp_damage);
ACMD(do_mp_deposit);
ACMD(do_mpdrop);
ACMD(do_mp_open_passage);
ACMD(do_mp_practice);
ACMD(do_mp_restore);
ACMD(do_mp_slay);
ACMD(do_mp_withdraw);
ACMD(do_mpadvance);
ACMD(do_mpapply);
ACMD(do_mpapplyb);
ACMD(do_mpasound);
ACMD(do_mpat);
ACMD(do_mpdelvar);
ACMD(do_mpdispel);
ACMD(do_mpdream);
ACMD(do_mpecho);
ACMD(do_mpechoall);
ACMD(do_mpechoaround);
ACMD(do_mpechoat);
ACMD(do_mpedit);
ACMD(do_mpexp);
ACMD(do_mpfavor);
ACMD(do_mpfear);
ACMD(do_mpforce);
ACMD(do_mpgoto);
ACMD(do_mphate);
ACMD(do_mphunt);
ACMD(do_mpinvis);
ACMD(do_mpjunk);
ACMD(do_mpkill);
ACMD(do_mpmload);
ACMD(do_mpmodvar);
ACMD(do_mpmset);
ACMD(do_mpmtransform);
ACMD(do_mpnothing);
ACMD(do_mpoload);
ACMD(do_mposet);
ACMD(do_mpotransform);
ACMD(do_mppeace);
ACMD(do_mppkset);
ACMD(do_mppurge);
ACMD(do_mpsetvar);
ACMD(do_mpstat);
ACMD(do_mptransfer);
ACMD(do_mrange);
ACMD(do_mset);
ACMD(do_msfind);
ACMD(do_mslist);
ACMD(do_mstat);
ACMD(do_multiclasses);
ACMD(do_muse);
ACMD(do_music);
ACMD(do_mwhere);
#endif
#if defined(TABLES_C_N) || defined(TABLES_C_ALL)
ACMD(do_name);
ACMD(do_netstat);
ACMD(do_newbiechat);
ACMD(do_new_ch_class);
ACMD(do_newbieset);
ACMD(do_newzones);
ACMD(do_nickname);
ACMD(do_noemote);
ACMD(do_noooc);
ACMD(do_noresolve);
ACMD(do_north);
ACMD(do_northeast);
ACMD(do_northwest);
ACMD(do_notell);
ACMD(do_noteroom);
ACMD(do_notitle);
#endif
#if defined(TABLES_C_O) || defined(TABLES_C_ALL)
ACMD(do_oassign);
ACMD(do_ocreate);
ACMD(do_odelete);
ACMD(do_offer);
ACMD(do_ofind);
/*ACMD(do_ogrub);*/
ACMD(do_olist);
#ifdef IBUILD
ACMD(do_omenu);
#endif
ACMD(do_ooc);
ACMD(do_opedit);
ACMD(do_open);
/*ACMD(do_opentourney);*/
ACMD(do_opstat);
ACMD(do_orange);
ACMD(do_order);
ACMD(do_orders);
ACMD(do_ordertalk);
ACMD(do_oset);
ACMD(do_osfind);
ACMD(do_oslist);
ACMD(do_ostat);
ACMD(do_outcast);
ACMD(do_owhere);
#endif
#if defined(TABLES_C_P) || defined(TABLES_C_ALL)
#ifdef IBUILD
ACMD(do_pagelen);
#endif
ACMD(do_pager);
ACMD(do_pardon);
ACMD(do_password);
ACMD(do_peace);
ACMD(do_pick);
ACMD(do_planes);
ACMD(do_poison_weapon);
ACMD(do_portal);
ACMD(do_pose);
ACMD(do_practice);
ACMD(do_pray);
ACMD(do_probability_travel);
ACMD(do_prompt);
ACMD(do_property);
ACMD(do_propset);
ACMD(do_propstat);
ACMD(do_psicrush);
ACMD(do_psidisintegrate);
ACMD(do_psiscry);
ACMD(do_psisummon);
ACMD(do_psiteleport);
ACMD(do_psitrain);
ACMD(do_pstat);
ACMD(do_pull);
ACMD(do_punch);
ACMD(do_purge);
ACMD(do_push);
ACMD(do_put);
#endif
#if defined(TABLES_C_Q) || defined(TABLES_C_ALL)
ACMD(do_qpset);
ACMD(do_quaff);
ACMD(do_quest);
ACMD(do_quests);
ACMD(do_questtalk);
ACMD(do_qui);
ACMD(do_quit);
ACMD(do_quivering_palm);
#endif
#if defined(TABLES_C_R) || defined(TABLES_C_ALL)
ACMD(do_races);
ACMD(do_rank);
ACMD(do_rareobjs);
ACMD(do_rassign);
ACMD(do_rat);
ACMD(do_rdelete);
ACMD(do_read);
ACMD(do_reassigncmd);
ACMD(do_reboo);
ACMD(do_reboot);
ACMD(do_recall);
ACMD(do_recho);
ACMD(do_recite);
ACMD(do_recognize);
#ifdef IBUILD
ACMD(do_redraw_page);
ACMD(do_refresh_page);
#endif
ACMD(do_regoto);
ACMD(do_remove);
ACMD(do_rent);
ACMD(do_repair);
ACMD(do_repairset);
ACMD(do_repairshops);
ACMD(do_repairstat);
ACMD(do_reply);
ACMD(do_report);
ACMD(do_rescue);
ACMD(do_reset);
ACMD(do_resolve);
ACMD(do_rest);
ACMD(do_restore);
ACMD(do_restoretime);
ACMD(do_restrict);
ACMD(do_retire);
ACMD(do_retran);
ACMD(do_return);
ACMD(do_revert);
ACMD(do_rfind);
ACMD(do_rip);
ACMD(do_rlist);
#ifdef IBUILD
ACMD(do_rmenu);
#endif
ACMD(do_rpedit);
ACMD(do_rpstat);
ACMD(do_rreset);
ACMD(do_rset);
ACMD(do_rsfind);
ACMD(do_rslist);
ACMD(do_rstat);
ACMD(do_run);
#endif
#if defined(TABLES_C_S) || defined(TABLES_C_ALL)
ACMD(do_sacrifice);
ACMD(do_save);
ACMD(do_savearea);
ACMD(do_say);
ACMD(do_scan);
ACMD(do_scatter);
ACMD(do_score);
ACMD(do_scribe);
ACMD(do_search);
ACMD(do_sedit);
ACMD(do_sell);
ACMD(do_sendcl);
ACMD(do_set_boot_time);
ACMD(do_setclan);
ACMD(do_setch_class);
ACMD(do_setcouncil);
ACMD(do_setcurrency);
ACMD(do_setdeity);
ACMD(do_setseverity);
ACMD(do_setweather);
ACMD(do_shops);
ACMD(do_shopset);
ACMD(do_shopstat);
ACMD(do_shout);
ACMD(do_shove);
ACMD(do_show);
ACMD(do_showclan);
ACMD(do_showch_class);
ACMD(do_showcouncil);
ACMD(do_showdeity);
ACMD(do_showweather);
ACMD(do_shutdow);
ACMD(do_shutdown);
ACMD(do_silence);
ACMD(do_sit);
ACMD(do_sla);
ACMD(do_slay);
ACMD(do_sleep);
ACMD(do_slice);
ACMD(do_slist);
ACMD(do_slookup);
ACMD(do_smaug_chess);
ACMD(do_smaug_skill);
ACMD(do_smoke);
ACMD(do_sneak);
ACMD(do_snoop);
ACMD(do_sober);
ACMD(do_socials);
ACMD(do_south);
ACMD(do_southeast);
ACMD(do_southwest);
ACMD(do_speak);
ACMD(do_split);
ACMD(do_sset);
ACMD(do_stand);
ACMD(do_stats);
/*ACMD(do_starttourney);*/
ACMD(do_steal);
ACMD(do_sting);
ACMD(do_strew);
ACMD(do_strip);
ACMD(do_stun);
ACMD(do_supplicate);
ACMD(do_switch);
#endif
#if defined(TABLES_C_T) || defined(TABLES_C_ALL)
ACMD(do_tag);
ACMD(do_tail);
ACMD(do_tamp);
ACMD(do_tan);
ACMD(do_tell);
ACMD(do_think);
ACMD(do_ticks);
ACMD(do_time);
ACMD(do_timecmd);
ACMD(do_title);
ACMD(do_track);
ACMD(do_transfer);
ACMD(do_trust);
ACMD(do_typo);
#endif
#if defined(TABLES_C_U) || defined(TABLES_C_ALL)
ACMD(do_ultra_blast);
ACMD(do_unfoldarea);
ACMD(do_unhell);
ACMD(do_unlock);
ACMD(do_unsilence);
ACMD(do_up);
ACMD(do_use);
ACMD(do_users);
#endif
#if defined(TABLES_C_V) || defined(TABLES_C_ALL)
ACMD(do_value);
ACMD(do_variables);
ACMD(do_visible);
ACMD(do_vnums);
ACMD(do_vsearch);
#endif
#if defined(TABLES_C_W) || defined(TABLES_C_ALL)
ACMD(do_wake);
ACMD(do_warcry);
ACMD(do_wartalk);
ACMD(do_wear);
ACMD(do_weather);
ACMD(do_west);
ACMD(do_where);
ACMD(do_whisper);
ACMD(do_who);
ACMD(do_whois);
ACMD(do_whozone);
ACMD(do_wimpy);
ACMD(do_withdrawl);
ACMD(do_wizhelp);
ACMD(do_wizlist);
ACMD(do_wizlock);
ACMD(do_world);
ACMD(do_write);
#endif
#if defined(TABLES_C_X) || defined(TABLES_C_ALL)
#endif
#if defined(TABLES_C_Y) || defined(TABLES_C_ALL)
#endif
#if defined(TABLES_C_Z) || defined(TABLES_C_ALL)
ACMD(do_zap);
ACMD(do_zones);
#endif
ACMD(skill_notfound);
#endif
